# Generated by Django 5.1.2 on 2025-01-09 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='balance',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='user',
            new_name='profileuser',
        ),
        migrations.DeleteModel(
            name='SavingsAccount',
        ),
    ]
